# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import transcriber_service_pb2 as transcriber__service__pb2


class TranscriberServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transcribe = channel.unary_unary(
                '/TranscriberService/Transcribe',
                request_serializer=transcriber__service__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=transcriber__service__pb2.TranscribeResponse.FromString,
                )
        self.DetectLanguage = channel.unary_unary(
                '/TranscriberService/DetectLanguage',
                request_serializer=transcriber__service__pb2.DetectLanguageRequest.SerializeToString,
                response_deserializer=transcriber__service__pb2.DetectLanguageResponse.FromString,
                )


class TranscriberServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Transcribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectLanguage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranscriberServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=transcriber__service__pb2.TranscribeRequest.FromString,
                    response_serializer=transcriber__service__pb2.TranscribeResponse.SerializeToString,
            ),
            'DetectLanguage': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectLanguage,
                    request_deserializer=transcriber__service__pb2.DetectLanguageRequest.FromString,
                    response_serializer=transcriber__service__pb2.DetectLanguageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TranscriberService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TranscriberService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TranscriberService/Transcribe',
            transcriber__service__pb2.TranscribeRequest.SerializeToString,
            transcriber__service__pb2.TranscribeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DetectLanguage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TranscriberService/DetectLanguage',
            transcriber__service__pb2.DetectLanguageRequest.SerializeToString,
            transcriber__service__pb2.DetectLanguageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
